version: '3.8'

services:
  yolov13-detection:
    build: .
    container_name: yolov13-detection-suite
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./videos:/app/videos
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
    devices:
      - /dev/video0:/dev/video0  # Webcam access
    restart: unless-stopped
    command: python webcam_detection_enhanced.py --models yolov13s.pt

  # Optional: GPU-enabled version
  yolov13-detection-gpu:
    build: .
    container_name: yolov13-detection-suite-gpu
    ports:
      - "8001:8000"
    volumes:
      - ./models:/app/models
      - ./videos:/app/videos
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    devices:
      - /dev/video0:/dev/video0
    runtime: nvidia
    restart: unless-stopped
    command: python webcam_detection_enhanced.py --models yolov13s.pt --device cuda

